version: "2"
services:
  app:
    image: final_app_demo
    links:
      - db
    ports:
      - "8000:8000"
    container_name: app_cont_demo

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .:/docker-entrypoint-initdb.d/:ro
    container_name: db_cont_demo
